<html lang="zh" class="no-js"><head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>图表</title>
    <link href="/assets/echart/css/gallery.css" rel="stylesheet">

</head>
<body id="bodyId">
<!--<a href="#0" class="cd-cart">
    <span>0</span>
</a>-->
<div id="contentId">
    <ul class="cd-gallery" id="ulId">
        <!--<li><div class="cd-single-item" id="id_6"></div><div class="cd-item-info"><b><a href="#0">图表信息</a></b></div></li>-->
        <li><div class="cd-single-item" id="id_27" _echarts_instance_="ec_1611490801122" style="-webkit-tap-highlight-color: transparent; user-select: none; position: relative;"><div style="position: relative; overflow: hidden; width: 350px; height: 300px; padding: 0px; margin: 0px; border-width: 0px;"><canvas data-zr-dom-id="zr_0" width="700" height="600" style="position: absolute; left: 0px; top: 0px; width: 350px; height: 300px; user-select: none; -webkit-tap-highlight-color: rgba(0, 0, 0, 0); padding: 0px; margin: 0px; border-width: 0px;"></canvas></div><div></div></div><div class="cd-item-info"><b><a href="#0">自定义图表标题0</a></b></div></li>
        <li><div class="cd-single-item" id="id_26" _echarts_instance_="ec_1611490801123" style="-webkit-tap-highlight-color: transparent; user-select: none; position: relative;"><div style="position: relative; overflow: hidden; width: 350px; height: 300px; padding: 0px; margin: 0px; border-width: 0px; cursor: default;"><canvas data-zr-dom-id="zr_0" width="700" height="600" style="position: absolute; left: 0px; top: 0px; width: 350px; height: 300px; user-select: none; -webkit-tap-highlight-color: rgba(0, 0, 0, 0); padding: 0px; margin: 0px; border-width: 0px;"></canvas></div><div style="position: absolute; display: none; border-style: solid; white-space: nowrap; z-index: 9999999; transition: left 0.4s cubic-bezier(0.23, 1, 0.32, 1) 0s, top 0.4s cubic-bezier(0.23, 1, 0.32, 1) 0s; background-color: rgba(50, 50, 50, 0.7); border-width: 0px; border-color: rgb(51, 51, 51); border-radius: 4px; color: rgb(255, 255, 255); font: 14px / 21px &quot;Microsoft YaHei&quot;; padding: 5px; left: 223px; top: 94px; pointer-events: none;">自定义3<br><span style="display:inline-block;margin-right:5px;border-radius:10px;width:10px;height:10px;background-color:#3b5ede;"></span>系列1: 300<br><span style="display:inline-block;margin-right:5px;border-radius:10px;width:10px;height:10px;background-color:#6a5acd;"></span>系列2: 600<br><span style="display:inline-block;margin-right:5px;border-radius:10px;width:10px;height:10px;background-color:#fea31e;"></span>系列3: 900<br><span style="display:inline-block;margin-right:5px;border-radius:10px;width:10px;height:10px;background-color:#7cb5ec;"></span>系列4: 1,200<br><span style="display:inline-block;margin-right:5px;border-radius:10px;width:10px;height:10px;background-color:#99cc33;"></span>系列5: 1,500</div></div><div class="cd-item-info"><b><a href="#0">自定义图表标题121</a></b></div></li>
        <li><div class="cd-single-item" id="id_25" _echarts_instance_="ec_1611490801124" style="-webkit-tap-highlight-color: transparent; user-select: none; position: relative;"><div style="position: relative; overflow: hidden; width: 350px; height: 300px; padding: 0px; margin: 0px; border-width: 0px;"><canvas data-zr-dom-id="zr_0" width="700" height="600" style="position: absolute; left: 0px; top: 0px; width: 350px; height: 300px; user-select: none; -webkit-tap-highlight-color: rgba(0, 0, 0, 0); padding: 0px; margin: 0px; border-width: 0px;"></canvas></div><div></div></div><div class="cd-item-info"><b><a href="#0">自定义图表标题2</a></b></div></li>
        <li><div class="cd-single-item" id="id_24" _echarts_instance_="ec_1611490801125" style="-webkit-tap-highlight-color: transparent; user-select: none; position: relative;"><div style="position: relative; overflow: hidden; width: 350px; height: 300px; padding: 0px; margin: 0px; border-width: 0px; cursor: default;"><canvas data-zr-dom-id="zr_0" width="700" height="600" style="position: absolute; left: 0px; top: 0px; width: 350px; height: 300px; user-select: none; -webkit-tap-highlight-color: rgba(0, 0, 0, 0); padding: 0px; margin: 0px; border-width: 0px;"></canvas></div><div></div></div><div class="cd-item-info"><b><a href="#0">自定义图表标题122</a></b></div></li>
        <li><div class="cd-single-item" id="id_23" _echarts_instance_="ec_1611490801126" style="-webkit-tap-highlight-color: transparent; user-select: none; position: relative;"><div style="position: relative; overflow: hidden; width: 350px; height: 300px; padding: 0px; margin: 0px; border-width: 0px; cursor: default;"><canvas data-zr-dom-id="zr_0" width="700" height="600" style="position: absolute; left: 0px; top: 0px; width: 350px; height: 300px; user-select: none; -webkit-tap-highlight-color: rgba(0, 0, 0, 0); padding: 0px; margin: 0px; border-width: 0px;"></canvas></div><div style="position: absolute; display: none; border-style: solid; white-space: nowrap; z-index: 9999999; transition: left 0.4s cubic-bezier(0.23, 1, 0.32, 1) 0s, top 0.4s cubic-bezier(0.23, 1, 0.32, 1) 0s; background-color: rgba(50, 50, 50, 0.7); border-width: 0px; border-color: rgb(51, 51, 51); border-radius: 4px; color: rgb(255, 255, 255); font: 14px / 21px &quot;Microsoft YaHei&quot;; padding: 5px; left: 87px; top: 206px; pointer-events: none;">自定义5: 500 <br>占比：33.33%</div></div><div class="cd-item-info"><b><a href="#0">自定义图表标题111</a></b></div></li>
        <li><div class="cd-single-item" id="id_22" _echarts_instance_="ec_1611490801127" style="-webkit-tap-highlight-color: transparent; user-select: none; position: relative;"><div style="position: relative; overflow: hidden; width: 350px; height: 300px; padding: 0px; margin: 0px; border-width: 0px;"><canvas data-zr-dom-id="zr_0" width="700" height="600" style="position: absolute; left: 0px; top: 0px; width: 350px; height: 300px; user-select: none; -webkit-tap-highlight-color: rgba(0, 0, 0, 0); padding: 0px; margin: 0px; border-width: 0px;"></canvas></div><div></div></div><div class="cd-item-info"><b><a href="#0">自定义图表890</a></b></div></li>
        <li><div class="cd-single-item" id="id_21" _echarts_instance_="ec_1611490801128" style="-webkit-tap-highlight-color: transparent; user-select: none; position: relative;"><div style="position: relative; overflow: hidden; width: 350px; height: 300px; padding: 0px; margin: 0px; border-width: 0px; cursor: default;"><canvas data-zr-dom-id="zr_0" width="700" height="600" style="position: absolute; left: 0px; top: 0px; width: 350px; height: 300px; user-select: none; -webkit-tap-highlight-color: rgba(0, 0, 0, 0); padding: 0px; margin: 0px; border-width: 0px;"></canvas></div><div style="position: absolute; display: none; border-style: solid; white-space: nowrap; z-index: 9999999; transition: left 0.4s cubic-bezier(0.23, 1, 0.32, 1) 0s, top 0.4s cubic-bezier(0.23, 1, 0.32, 1) 0s; background-color: rgba(50, 50, 50, 0.7); border-width: 0px; border-color: rgb(51, 51, 51); border-radius: 4px; color: rgb(255, 255, 255); font: 14px / 21px &quot;Microsoft YaHei&quot;; padding: 5px; left: 231px; top: 92px; pointer-events: none;">自定义3<br><span style="display:inline-block;margin-right:5px;border-radius:10px;width:10px;height:10px;background-color:#3b5ede;"></span>系列1: 300<br><span style="display:inline-block;margin-right:5px;border-radius:10px;width:10px;height:10px;background-color:#6a5acd;"></span>系列2: 600<br><span style="display:inline-block;margin-right:5px;border-radius:10px;width:10px;height:10px;background-color:#fea31e;"></span>系列3: 900</div></div><div class="cd-item-info"><b><a href="#0">自定义图表标题78</a></b></div></li>
        <li><div class="cd-single-item" id="id_20" _echarts_instance_="ec_1611490801129" style="-webkit-tap-highlight-color: transparent; user-select: none; position: relative;"><div style="position: relative; overflow: hidden; width: 350px; height: 300px; padding: 0px; margin: 0px; border-width: 0px; cursor: default;"><canvas data-zr-dom-id="zr_0" width="700" height="600" style="position: absolute; left: 0px; top: 0px; width: 350px; height: 300px; user-select: none; -webkit-tap-highlight-color: rgba(0, 0, 0, 0); padding: 0px; margin: 0px; border-width: 0px;"></canvas></div><div style="position: absolute; display: none; border-style: solid; white-space: nowrap; z-index: 9999999; transition: left 0.4s cubic-bezier(0.23, 1, 0.32, 1) 0s, top 0.4s cubic-bezier(0.23, 1, 0.32, 1) 0s; background-color: rgba(50, 50, 50, 0.7); border-width: 0px; border-color: rgb(51, 51, 51); border-radius: 4px; color: rgb(255, 255, 255); font: 14px / 21px &quot;Microsoft YaHei&quot;; padding: 5px; left: 161px; top: 155px; pointer-events: none;">自定义5<br><span style="display:inline-block;margin-right:5px;border-radius:10px;width:10px;height:10px;background-color:#3b5ede;"></span>系列1: 500</div></div><div class="cd-item-info"><b><a href="#0">自定义图表标题</a></b></div></li>
        <li><div class="cd-single-item" id="id_19" _echarts_instance_="ec_1611490801130" style="-webkit-tap-highlight-color: transparent; user-select: none; position: relative;"><div style="position: relative; overflow: hidden; width: 350px; height: 300px; padding: 0px; margin: 0px; border-width: 0px; cursor: default;"><canvas data-zr-dom-id="zr_0" width="700" height="600" style="position: absolute; left: 0px; top: 0px; width: 350px; height: 300px; user-select: none; -webkit-tap-highlight-color: rgba(0, 0, 0, 0); padding: 0px; margin: 0px; border-width: 0px;"></canvas></div><div></div></div><div class="cd-item-info"><b><a href="#0">自定义图表标</a></b></div></li>
        <li><div class="cd-single-item" id="id_18" _echarts_instance_="ec_1611490801131" style="-webkit-tap-highlight-color: transparent; user-select: none; position: relative;"><div style="position: relative; overflow: hidden; width: 350px; height: 300px; padding: 0px; margin: 0px; border-width: 0px;"><canvas data-zr-dom-id="zr_0" width="700" height="600" style="position: absolute; left: 0px; top: 0px; width: 350px; height: 300px; user-select: none; -webkit-tap-highlight-color: rgba(0, 0, 0, 0); padding: 0px; margin: 0px; border-width: 0px;"></canvas></div><div></div></div><div class="cd-item-info"><b><a href="#0">自定义图表标题98</a></b></div></li>
    </ul>
    <div class="nodata"></div>
</div>


<script type="text/javascript" src="/assets/echart/js/jquery-1.4.4.min.js"></script>
<script type="text/javascript" src="/assets/echart/js/echarts.js"></script>
<script type="text/javascript" src="/assets/echart/js/maps.js"></script>
<script type="text/javascript" src="/assets/echart/js/gallery.js"></script>
<!--Popup Lightbox Js-->

</body></html>